#!/bin/bash
# Shortcut to tune-network status / control
if [ -f /usr/local/sbin/tune-network ]; then
    /usr/local/sbin/tune-network "${1:-status}"
elif [ -f /etc/satset/tune-network.sh ]; then
    /etc/satset/tune-network.sh "${1:-status}"
else
    echo "Modul tune-network belum terpasang. Jalankan 'update' terlebih dahulu."
    echo -ne "\033[1;36mTekan tombol apa saja untuk kembali ke menu...\033[0m"
    read -n 1 -s -r
fi
