#!/bin/bash
clear
y='\033[1;33m'
BGX="\033[42m"
CYAN="\033[96m"
Putih="\033[97m"
RED='\033[0;31m'
NC='\033[0m'
green='\033[0;32m'
BIBlack='\033[1;90m'
BIGreen='\033[1;92m'
BIYellow='\033[1;93m'
BIBlue='\033[1;94m'
BIPurple='\033[1;95m'
BICyan='\033[1;96m'
BIWhite='\033[1;97m'
UWhite='\033[4;37m'
On_IPurple='\033[0;105m'
On_IRed='\033[0;101m'
IBlack='\033[0;90m'
IGreen='\033[0;92m'
IYellow='\033[0;93m'
IBlue='\033[0;94m'
IPurple='\033[0;95m'
ICyan='\033[0;96m'
IWhite='\033[0;97m'
GREENBO='\033[1;32m'
bgwhite='\e[40;97;1m'
bgred='\e[41;97;1m'
bggreen='\e[42;97;1m'
bgyellow='\e[43;97;1m'
bgmagenta='\e[45;97;1m'
bgblue='\e[46;97;1m'
bgblack='\e[47;30;1m'
w='\033[97m'
ORANGE='\033[0;34m'
Lime='\e[38;5;155m'
ungu="\e[38;5;99m"
clear
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${Lime}SETTINGS${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${ungu}[${BIWhite}01${ungu}] ${NC}${BIWhite}Restart All Service${NC}"
echo -e "${ungu}[${BIWhite}02${ungu}] ${NC}${BIWhite}Ganti UUID Xray${NC}"
echo -e "${ungu}[${BIWhite}03${ungu}] ${NC}${BIWhite}Setup Autoreboot${NC}"
echo -e "${ungu}[${BIWhite}04${ungu}] ${NC}${BIWhite}Autoreboot${NC}"
echo -e "${ungu}[${BIWhite}05${ungu}] ${NC}${BIWhite}Speedtest${NC}"
echo -e "${ungu}[${BIWhite}06${ungu}] ${NC}${BIWhite}On & OFF Limit IP & Quota${NC}"
echo -e "${ungu}[${BIWhite}07${ungu}] ${NC}${BIWhite}Check Ram & CPU${NC}"
echo -e "${ungu}[${BIWhite}08${ungu}] ${NC}${BIWhite}Info Port${NC}"
echo -e "${ungu}[${BIWhite}09${ungu}] ${NC}${BIWhite}Rebuild VPS${NC}"
echo -e "${ungu}[${BIWhite}10${ungu}] ${NC}${BIWhite}Status TCP BBR & Anti-DDoS${NC}"
echo -e "${ungu}[${BIWhite}11${ungu}] ${NC}${BIWhite}Status BadVPN UDPGW (Gaming)${NC}"
echo -e "${ungu}[${BIWhite}12${ungu}] ${NC}${BIWhite}Multi-Node Cluster / Node Agent${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${Lime}Input x atau 0 untuk kembali ke Menu Utama${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo ""
echo -ne "\033[1;36mSelect menu [01-12] or [x]: \033[0m"
read -r opt
echo -e ""
case $opt in
1|01) clear ; restart ;;
2|02) clear ; ganti-id ;;
3|03) clear ; setupreboot ;;
4|04) clear ; autoreboot ;;
5|05) clear ; speedtest ; echo -ne "\033[1;36mPress [ Enter ] to back on menu...\033[0m" ; read -n 1 -s -r ; m-setting ;;
6|06) clear ; m-mulog ;;
7|07) clear ; gotop ; echo -ne "\033[1;36mPress [ Enter ] to back on menu...\033[0m" ; read -n 1 -s -r ; m-setting ;;
8|08) clear ; prot ;;
9|09) clear ; m-rebuild ;;
10|10) clear ; bbr ; m-setting ;;
11|11) clear ; badvpn ; m-setting ;;
12|12) clear ; m-node ; m-setting ;;
0|00) clear ; menu ; exit ;;
x|X) menu ;;
*) echo "Pilihan tidak valid." ; sleep 1 ; m-setting ;;
esac